name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for git-related tests
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc
    
    - name: Make scripts executable
      run: |
        chmod +x context git-context apply-md
        chmod +x test/test_runner.sh
        chmod +x test/unit/test_*.sh
    
    - name: Run tests
      run: |
        ./test/test_runner.sh

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Shell script linting
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        shellcheck -x context git-context apply-md
        shellcheck -x test/test_runner.sh
        shellcheck -x test/test_utils.sh
        shellcheck -x test/unit/test_*.sh

  compatibility:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Make scripts executable
      run: |
        chmod +x context
        chmod +x test/test_runner.sh
        chmod +x test/unit/test_*.sh
    
    - name: Run tests on ${{ matrix.os }}
      run: |
        ./test/test_runner.sh
